# Generated by Django 4.2.1 on 2023-05-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_alter_category_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
