# Generated by Django 4.2.1 on 2023-05-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_alter_artwork_image_alter_page_page_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='banner',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
