# Generated by Django 4.2.1 on 2023-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0010_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='public_id',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
