# Generated by Django 4.2.1 on 2023-06-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_category_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
